<a href="https://colab.research.google.com/github/AramisRamirezITT/RDI_2022/blob/main/Aramis_Ramirez_Tarea_2_Linear_Algebra_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 2 PDI 2020
## UAG

Sea:


$$
a = \left(\begin{array}{cc} 
 2\\ 
4
\end{array}\right)
$$ 


$$
b = \left(\begin{array}{cc} 
3 & 2
\end{array}\right)
$$ 


$$
A = \left(\begin{array}{cc} 
2 & 3 \\
4 & 1
\end{array}\right)
$$ 

$$
B = \left(\begin{array}{cc} 
3 & -2 \\
4 & -1
\end{array}\right)
$$ 

Hacer las siguientes operaciones (**si existen!!!!!**)

1   $ a + b$

2   $ a + b'$  en que $b'$ en la transpuesta de $b$

3   $ ab$

4   $ ba$

5  $b/a$

6  $5a$

7 $AB$

8 $BA$

9 $3\exp(A)^{0.5}$ 

10 $A^{-1}$

11 $Det(B)$

12 $B/b$


In [34]:
import numpy as np


In [35]:
a = np.array( [[2],
              [4]])

b = np.array([[3, 2]])

A = np.array([[2,3], 
     [4,1]])

B = np.array([[3,-2], 
     [4,-1]])

# B

#No es posible la suma a + b debido que no son de la misma dimencion 

In [36]:
# a + b'

t = np.transpose(b)

resul = a + t

resul

array([[5],
       [6]])

In [37]:
# a*b

mult_1 = a * b
mult_1

array([[ 6,  4],
       [12,  8]])

In [38]:
# b*a

mult_2 = np.multiply(b,a)
mult_2

array([[ 6,  4],
       [12,  8]])

#a/b no es posible devido a las dimenciones de las matrices 

In [44]:
#5*a

mult_escalar = 5*a

mult_escalar

array([[10],
       [20]])

In [48]:
#AB

mult_2x2_1 = np.multiply(A,B)

mult_2x2_1 


array([[ 6, -6],
       [16, -1]])

In [49]:
#BA

mult_2x2_2 = np.multiply(B,A)

mult_2x2_2

array([[ 6, -6],
       [16, -1]])

In [56]:
#3exp(A)0.5

expo = np.exp(A)
result_expo = 3 * (expo) ** 0.5

result_expo

array([[ 8.15484549, 13.44506721],
       [22.1671683 ,  4.94616381]])

In [51]:
#A^−1

inversa = np.linalg.inv(A)

inversa

array([[-0.1,  0.3],
       [ 0.4, -0.2]])

In [52]:
#Det(B)

determinante = np.linalg.det(B)
determinante


4.999999999999999

#B/b
#div = b^-1*B  

No es posible porque la 'b' no tiene inversa 